---
- name: Create service accounts
  k8s:
    state: present
    definition:
      kind: ServiceAccount
      apiVersion: v1
      metadata:
        name: "{{ item }}"
        namespace: "{{ osbs_ocp_namespace }}"
  with_items:
    - "{{ osbs_list_sa }}"
  tags:
    - deployment-sa


- name: Create rolebindings
  k8s:
    state: present
    definition:
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "{{ item.name }}-rolebinding"
        namespace: "{{ osbs_ocp_namespace }}"
      subjects:
        - kind: "{{ item.kind }}"
          name: "{{ item.name }}"
          namespace: "{{ osbs_ocp_namespace }}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: "{{ item.role }}"
  with_items:
    - "{{ osbs_list_of_dict_rolebindings }}"
  tags:
    - deployment-sa


- name: "Create secrets"
  no_log: true
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: "{{ item.type }}"
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ osbs_ocp_namespace }}"
      data:
        "{{ item.data }}"
  with_items:
    - "{{ osbs_list_of_dict_secrets }}"
  tags:
    - osbs-secrets


- name: Create configmaps
  k8s:
    state: present
    definition:
      apiVersion: v1
      data:
        config.yaml: |
          {{ item.data | to_nice_yaml }}
      kind: ConfigMap
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ osbs_ocp_namespace }}"
  with_items: "{{ osbs_reactor_config_maps }}"
  tags:
    - configmaps


- name: Deploy pipeline tasks
  k8s:
    state: present
    apply: true
    namespace: "{{ osbs_ocp_namespace }}"
    definition: "{{ lookup('url', '{{ item }}', split_lines=False) | from_yaml_all | list }}"
  with_items: "{{ osbs_tasks_definitions }}"
  tags:
    - tasks


- name: Deploy pipelines
  k8s:
    state: present
    apply: true
    namespace: "{{ osbs_ocp_namespace }}"
    definition: "{{ lookup('url', '{{ item }}', split_lines=False) | from_yaml_all | list }}"
  with_items: "{{ osbs_pipelines_definitions }}"
  tags:
    - pipelines


- name: Create PipelineRun cleaning CronJob
  k8s:
    state: present
    namespace: "{{ osbs_ocp_namespace }}"
    definition:
      apiVersion: batch/v1beta1
      kind: CronJob
      metadata:
        name: "{{ item.name }}"
      spec:
        schedule: "{{ pipeline_run_pruning_schedule }}"
        jobTemplate:
          spec:
            template:
              spec:
                serviceAccountName: "{{ osbs_pruner_sa }}"
                containers:
                  - name: "{{ item.name }}"
                    image: "{{ cronjob_image }}"
                    args:
                      - /bin/sh
                      - '-c'
                      - "{{ item.template }}"
                    resources:
                      requests:
                        cpu: 10m
                        memory: 128Mi
                      limits:
                        cpu: 25m
                        memory: 256Mi
                restartPolicy: OnFailure
  with_items:
    - {name: "pipelinerun-cleaner", template: "{{ lookup('template', 'templates/pipeline_run_pruner.sh') }}"}
  tags:
    - cronjobs


- name: Create Pod cleaning CronJob
  k8s:
    state: present
    namespace: "{{ osbs_ocp_namespace }}"
    definition:
      apiVersion: batch/v1beta1
      kind: CronJob
      metadata:
        name: "{{ item.name }}"
      spec:
        schedule: "{{ pod_pruning_schedule }}"
        jobTemplate:
          spec:
            template:
              spec:
                serviceAccountName: "{{ osbs_pruner_sa }}"
                containers:
                  - name: "{{ item.name }}"
                    image: "{{ cronjob_image }}"
                    args:
                      - /bin/sh
                      - '-c'
                      - "{{ item.template }}"
                    resources:
                      requests:
                        cpu: 10m
                        memory: 128Mi
                      limits:
                        cpu: 25m
                        memory: 256Mi
                restartPolicy: OnFailure
  with_items:
    - {name: "pod-pruner", template: "{{ lookup('template', 'templates/pod_pruner.sh') }}"}
  tags:
    - cronjobs
