---
- name: Create service accounts
  k8s:
    state: present
    definition:
      kind: ServiceAccount
      apiVersion: v1
      metadata:
        name: "{{ item }}"
        namespace: "{{ osbs_ocp_namespace }}"
  with_items:
    - "{{ osbs_list_sa }}"
  tags:
  - deployment-sa


- name: Create rolebindings for service accounts
  k8s:
    state: present
    definition:
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "{{ item.sa_name }}-rolebinding"
        namespace: "{{ osbs_ocp_namespace }}"
      subjects:
        - kind: ServiceAccount
          name: "{{ item.sa_name }}"
          namespace: "{{ osbs_ocp_namespace }}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: "{{ item.role }}"
  with_items:
    - "{{ osbs_list_of_dict_sa_with_roles }}"
  tags:
  - deployment-sa


- name: "Create secrets"
  no_log: true
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: "{{ item.type }}"
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ osbs_ocp_namespace }}"
      data:
        "{{ item.data }}"
  with_items:
    - "{{ osbs_list_of_dict_secrets }}"
  tags:
  - osbs-secrets


# TODO: Cluster role: Admin does not have permissions to create/adjust limitranges!
- name: Add limitrange for namespace
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/limit_range.yml') | from_yaml }}"
  tags:
  - limit-range


- name: Create configmaps
  k8s:
    state: present
    definition:
      apiVersion: v1
      data:
        config.yaml: |
          {{ item.data | to_nice_yaml }}
      kind: ConfigMap
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ osbs_ocp_namespace }}"
  with_items: "{{ osbs_reactor_config_maps }}"
  tags:
  - configmaps


- name: Deploy pipeline tasks
  k8s:
    state: present
    apply: yes
    namespace: "{{ osbs_ocp_namespace }}"
    definition: "{{ lookup('url', '{{ item }}', split_lines=False) | from_yaml_all | list }}"
  with_items: "{{ osbs_tasks_definitions }}"
  tags:
  - tasks


- name: Deploy pipelines
  k8s:
    state: present
    apply: yes
    namespace: "{{ osbs_ocp_namespace }}"
    definition: "{{ lookup('url', '{{ item }}', split_lines=False) | from_yaml_all | list }}"
  with_items: "{{ osbs_pipelines_definitions }}"
  tags:
  - pipelines


- name: Create PipelineRun cleaning CronJob
  k8s:
    state: present
    namespace: "{{ osbs_ocp_namespace }}"
    definition:
      apiVersion: batch/v1beta1
      kind: CronJob
      metadata:
        name: pipelinerun-cleaner
      spec:
        # every 5 min
        schedule: "*/5 * * * *"
        jobTemplate:
          spec:
            template:
              spec:
                serviceAccountName: "{{ osbs_pruner_sa }}"
                containers:
                  - name: tkn
                    image: registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8:0.19.0-2
                    command: ["tkn", "pipelinerun", "delete", "-n", "{{ osbs_ocp_namespace }}", "-f", "--all"]
                    resources:
                      requests:
                        cpu: 10m
                        memory: 128Mi
                      limits:
                        cpu: 25m
                        memory: 256Mi
                restartPolicy: OnFailure
  tags:
  - pipeline-pruner


- name: Create Pod cleaning CronJob
  k8s:
    state: present
    namespace: "{{ osbs_ocp_namespace }}"
    definition:
      apiVersion: batch/v1beta1
      kind: CronJob
      metadata:
        name: "{{ item.name }}"
      spec:
        # hourly
        schedule: "0 * * * *"
        jobTemplate:
          spec:
            template:
              spec:
                serviceAccountName: "{{ osbs_pruner_sa }}"
                containers:
                  - name: "{{ item.name }}"
                    image: "{{ cronjob_image }}"
                    args:
                      - /bin/sh
                      - '-c'
                      - "{{ item.template }}"
                    resources:
                      requests:
                        cpu: 10m
                        memory: 128Mi
                      limits:
                        cpu: 25m
                        memory: 256Mi
                restartPolicy: OnFailure
  with_items:
    - { name: "pod-pruner", template: "{{ lookup('template', 'templates/pod_pruner.sh') }}"}
  tags:
  - cronjobs
