- import_tasks: tasks/generic/cronjob.yml
  vars:
    osbs_generic_cronjob_name: remove-unused-istags
    osbs_generic_cronjob_serviceaccount: "{{ osbs_pruner_serviceaccount }}"
    osbs_generic_cronjob_schedule: "{{ osbs_pruner_schedule_istags }}"
    osbs_generic_cronjob_successful_jobs: "{{ osbs_pruner_successful_jobs }}"
    osbs_generic_cronjob_failed_jobs: "{{ osbs_pruner_failed_jobs }}"
    osbs_generic_cronjob_image: "{{ osbs_pruner_custom_image }}"
    osbs_generic_cronjob_command: "{{ osbs_pruner_command_istags }}"

- import_tasks: tasks/generic/cronjob.yml
  vars:
    osbs_generic_cronjob_name: pruner-imagestreams
    osbs_generic_cronjob_serviceaccount: "{{ osbs_pruner_serviceaccount }}"
    osbs_generic_cronjob_schedule: "{{ osbs_pruner_schedule_imagestreams }}"
    osbs_generic_cronjob_successful_jobs: "{{ osbs_pruner_successful_jobs }}"
    osbs_generic_cronjob_failed_jobs: "{{ osbs_pruner_failed_jobs }}"
    osbs_generic_cronjob_image: "{{ osbs_pruner_custom_image }}"
    osbs_generic_cronjob_command: "{{ osbs_pruner_command_imagestreams }}"
