# Parameters:
# osbs_generic_cronjob_name
# osbs_generic_cronjob_serviceaccount
# osbs_generic_cronjob_schedule
# osbs_generic_cronjob_successful_jobs
# osbs_generic_cronjob_failed_jobs
# osbs_generic_cronjob_image
# osbs_generic_cronjob_command

- name: Copy {{ osbs_generic_cronjob_name }} cron job
  template:
    src: cronjob.yaml.j2
    dest: "{{ osbs_openshift_home }}/{{ inventory_hostname }}-{{ osbs_namespace }}-{{ osbs_generic_cronjob_name }}-cronjob.yml"
  register: yaml_cj
  tags:
  - oc

- name: Import {{ osbs_generic_cronjob_name }} cron job
  command: >
    oc replace
    --namespace={{ osbs_namespace}}
    --force=true
    --filename={{ osbs_openshift_home }}/{{ inventory_hostname }}-{{ osbs_namespace }}-{{ osbs_generic_cronjob_name }}-cronjob.yml
  environment: "{{ osbs_environment }}"
  when: yaml_cj.changed
  tags:
  - oc
