# Parameters:
# osbs_generic_serviceaccount_name

- name: Copy {{ osbs_generic_serviceaccount_name }} service account definition
  template:
    src: openshift-serviceaccount.yml.j2
    dest: "{{ osbs_openshift_home }}/{{ inventory_hostname }}-{{ osbs_namespace }}-serviceaccount-{{ item }}.yml"
  register: yaml_sa
  with_items:
  - "{{ osbs_generic_serviceaccount_name }}"
  tags:
  - oc

- name: Import {{ osbs_generic_serviceaccount_name }} service account
  command: >
    oc create
    --namespace={{ osbs_namespace }}
    --filename={{ osbs_openshift_home }}/{{ inventory_hostname }}-{{ osbs_namespace }}-serviceaccount-{{ osbs_generic_serviceaccount_name }}.yml
  register: service_account_import
  failed_when: service_account_import.rc != 0 and ('already exists' not in service_account_import.stderr)
  environment: "{{ osbs_environment }}"
  when: yaml_sa.changed
  tags:
  - oc
