---
- name: Set LimitNOFILE in atomic-openshift-node
  lineinfile:
    path: /etc/systemd/system/atomic-openshift-node.service
    regexp: '^LimitNOFILE='
    line: 'LimitNOFILE={{ osbs_systemd_limit_nofile }}'
    backup: yes
  notify:
  - restart atomic-openshift-node

- name: set LimitNOFILE /etc/systemd/system.conf
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: 'DefaultLimitNOFILE='
    line: 'DefaultLimitNOFILE={{ osbs_systemd_limit_nofile }}'
    backup: yes

- name: restart systemd
  command: systemctl daemon-reexec

- meta: flush_handlers
