name: "KICS"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "56 22 * * 2"

jobs:
  kics-analyze:
    name: KICS-Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Mkdir results-dir
      # make sure results dir is created
      run: mkdir -p results-dir
    - name: Run kics Scan
      uses: Checkmarx/kics-github-action@v1.6
      with:
        path: 'tasks,defaults,meta'
        platform_type: ansible
        output_path: results-dir
        output_formats: 'json,sarif'
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results-dir/results.sarif
